### ISSUE TITLE
Were is da files?

### ISSUE THREAD

**Issue by JohnAndante** [GrecoMS0/ProjetosAlura#1]
# Da files is missingue, were is da files????

**Comment by JohnAndante** [comment]
filés stil missengue. Were is da files?? ⚽

**Comment by GrecoMS0** [comment]
Da files is corromped by víros, need to recuperar da files quick!!!

**Comment by JohnAndante** [comment]
nissaan 🚗🚗

**Comment by JohnAndante** [comment]
> nissaan 🚗🚗
![NissanLogoNissanGIF](https://github.com/GrecoMS0/ProjetosAlura/assets/53200345/0f759847-1675-4821-8b90-18b939ad6b27)
